<?php

namespace Database\Seeders;

use App\Models\Mahasiswa;
use Illuminate\Database\Seeder;

class MahasiswaSeederII extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect([
            // MI23A
            // 1
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302002',
                'nama'          => 'Aceng Ziran Fauji',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 2
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302074',
                'nama'          => 'Yogi Febriandi',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 3
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302049',
                'nama'          => 'Tazkia Hidayatuloh AL M.',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 4
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302034',
                'nama'          => 'Andika Herviantino P.',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 5
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302050',
                'nama'          => 'Sinta Aulia Wardani',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 6
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '9',
                'nim'           => '202302057',
                'nama'          => 'Arafian Hafiz',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'BPH',
                'alasan'        => '-',
            ],
            // 7
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302029',
                'nama'          => 'Rian Afrizal',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 8
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '11',
                'nim'           => '202302053',
                'nama'          => 'Dimas Novi Fitriansyah',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'BPH',
                'alasan'        => '-',
            ],
            // 9
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302039',
                'nama'          => 'Rangga Dwiky Rokhman P.',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],
            // 10
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302015',
                'nama'          => 'Emil Awaliadi',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 11
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '11',
                'nim'           => '202302094',
                'nama'          => 'Puji Haryadi',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'BPH',
                'alasan'        => '-',
            ],
            // 12
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302003',
                'nama'          => 'Fazhari Rizky',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],
            // 13
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302005',
                'nama'          => 'Muhammad Rasyid Ridho',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 14
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302054',
                'nama'          => 'Kevin Leonardo',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 15
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302016',
                'nama'          => 'Muhammad Farhan Saefulloh',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 16
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302064',
                'nama'          => 'Muhamad Arfan Maulana',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 17
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '10',
                'nim'           => '202302056',
                'nama'          => 'Muhammad Ali Akbar A. A.',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'BPH',
                'alasan'        => '-',
            ],
            // 18
            [
                'kelas_id'      => '6',
                'jabatan_id'    => '1',
                'nim'           => '202302088',
                'nama'          => 'Muhamad Irfan Sujono',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // End MI23A

            // MI23B
            // 1
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '3',
                'nim'           => '202302028',
                'nama'          => 'Adi Aprianto',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'BPH',
                'alasan'        => '-',
            ],
            // 2
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '8',
                'nim'           => '202302035',
                'nama'          => 'Teguh Afriansyah',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'BPH',
                'alasan'        => '-',
            ],
            // 3
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302037',
                'nama'          => 'Azwan Faisal',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 4
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302000',
                'nama'          => 'Shandy Febriansyah',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 5
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302086',
                'nama'          => 'Dede Muhammad Walid A.',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 6
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302059',
                'nama'          => 'Rizki Firdaus',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 7
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302060',
                'nama'          => 'Deki Inawan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 8
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '5',
                'nim'           => '202302004',
                'nama'          => 'Reni Nurhayni',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'BPH',
                'alasan'        => '-',
            ],
            // 9
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '2023020',
                'nama'          => 'Djohara Ariefin Haqim H.',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 10
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302051',
                'nama'          => 'Raga Kusnira',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 11
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302006',
                'nama'          => 'Ikhsan Tazkia Muhammad F.',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 12
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302077',
                'nama'          => 'Muhammad Rafi Assidiqi',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 13
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '2',
                'nim'           => '202302036',
                'nama'          => 'Khikmal Kurniawan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'BPH',
                'alasan'        => '-',
            ],
            // 14
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302040',
                'nama'          => 'Muhammad Arfan Algibrani',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 15
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302055',
                'nama'          => 'Mohammad Khalil Ardhani',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],
            // 16
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302033',
                'nama'          => 'Muhammad Abdur Rouf',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 17
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '202302087',
                'nama'          => 'Muhamad Faisal Abdallah',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 18
            [
                'kelas_id'      => '7',
                'jabatan_id'    => '1',
                'nim'           => '20230201',
                'nama'          => 'Panja Alzikri Hidayat',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => '-',
                'tanggal_lahir' => '2000-01-01',
                'alamat'        => '-',
                'asal_sekolah'  => '-',
                'jurusan'       => '-',
                'no_telpon'     => '000000000000',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],
            // End MI23B

            // MP04
            [
                // 1
                'kelas_id'      => '8',
                'jabatan_id'    => '1',
                'nim'           => '837462787',
                'nama'          => 'Ahmad Fauzi',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2001-05-21',
                'alamat'        => 'Jl. Merdeka No. 12',
                'asal_sekolah'  => 'SMAN 1 Jakarta',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '08123456789',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],
            [
                // 2
                'kelas_id'      => '8',
                'jabatan_id'    => '1',
                'nim'           => '87654321',
                'nama'          => 'Siti Nurhaliza',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Bandung',
                'tanggal_lahir' => '2000-11-12',
                'alamat'        => 'Jl. Sudirman No. 45',
                'asal_sekolah'  => 'SMAN 3 Bandung',
                'jurusan'       => 'Manajemen',
                'no_telpon'     => '08234567890',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],
            [
                // 3
                'kelas_id'      => '8',
                'jabatan_id'    => '1',
                'nim'           => '11223344',
                'nama'          => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Surabaya',
                'tanggal_lahir' => '1999-03-14',
                'alamat'        => 'Jl. Diponegoro No. 67',
                'asal_sekolah'  => 'SMAN 2 Surabaya',
                'jurusan'       => 'Akuntansi',
                'no_telpon'     => '08345678901',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            [
                // 4
                'kelas_id'      => '8',
                'jabatan_id'    => '1',
                'nim'           => '625339187',
                'nama'          => 'Dewi Anggraeni',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Yogyakarta',
                'tanggal_lahir' => '2002-08-30',
                'alamat'        => 'Jl. Malioboro No. 21',
                'asal_sekolah'  => 'SMAN 4 Yogyakarta',
                'jurusan'       => 'Ilmu Komunikasi',
                'no_telpon'     => '08456789012',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // MKP04
            // 1
            [
                'kelas_id'      => '9',
                'jabatan_id'    => '1',
                'nim'           => '33445566',
                'nama'          => 'Rizki Ramadhan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Semarang',
                'tanggal_lahir' => '2001-09-14',
                'alamat'        => 'Jl. Pahlawan No. 78',
                'asal_sekolah'  => 'SMAN 5 Semarang',
                'jurusan'       => 'Teknik Sipil',
                'no_telpon'     => '08567890123',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 2
            [
                'kelas_id'      => '9',
                'jabatan_id'    => '1',
                'nim'           => '99887766',
                'nama'          => 'Nur Aisyah',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Makassar',
                'tanggal_lahir' => '2002-06-18',
                'alamat'        => 'Jl. Hasanuddin No. 33',
                'asal_sekolah'  => 'SMAN 1 Makassar',
                'jurusan'       => 'Sistem Informasi',
                'no_telpon'     => '08678901234',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 3
            [
                'kelas_id'      => '9',
                'jabatan_id'    => '1',
                'nim'           => '44556671',
                'nama'          => 'Andi Pratama',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Medan',
                'tanggal_lahir' => '2000-12-24',
                'alamat'        => 'Jl. Sisingamangaraja No. 9',
                'asal_sekolah'  => 'SMAN 7 Medan',
                'jurusan'       => 'Ekonomi',
                'no_telpon'     => '08789012345',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // AB17
            // 1
            [
                'kelas_id'      => '10',
                'jabatan_id'    => '1',
                'nim'           => '982734400',
                'nama'          => 'Fajar Setiawan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Malang',
                'tanggal_lahir' => '2003-02-17',
                'alamat'        => 'Jl. Ijen No. 45',
                'asal_sekolah'  => 'SMAN 2 Malang',
                'jurusan'       => 'Teknik Elektro',
                'no_telpon'     => '08901234567',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 2
            [
                'kelas_id'      => '10',
                'jabatan_id'    => '1',
                'nim'           => '22334455',
                'nama'          => 'Indah Permata',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Bali',
                'tanggal_lahir' => '2001-07-09',
                'alamat'        => 'Jl. Kuta No. 12',
                'asal_sekolah'  => 'SMAN 1 Denpasar',
                'jurusan'       => 'Pariwisata',
                'no_telpon'     => '08123456780',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 3
            [
                'kelas_id'      => '10',
                'jabatan_id'    => '1',
                'nim'           => '77889900',
                'nama'          => 'Siti Aminah',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Palembang',
                'tanggal_lahir' => '2002-11-20',
                'alamat'        => 'Jl. Kapten A. Rivai No. 21',
                'asal_sekolah'  => 'SMAN 4 Palembang',
                'jurusan'       => 'Biologi',
                'no_telpon'     => '08234567891',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 4
            [
                'kelas_id'      => '10',
                'jabatan_id'    => '1',
                'nim'           => '66778899',
                'nama'          => 'Hendra Wijaya',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Pontianak',
                'tanggal_lahir' => '2000-04-12',
                'alamat'        => 'Jl. Ahmad Yani No. 10',
                'asal_sekolah'  => 'SMAN 3 Pontianak',
                'jurusan'       => 'Kimia',
                'no_telpon'     => '08567890124',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 5
            [
                'kelas_id'      => '10',
                'jabatan_id'    => '1',
                'nim'           => '99001122',
                'nama'          => 'Rina Setiani',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Bandar Lampung',
                'tanggal_lahir' => '2001-03-30',
                'alamat'        => 'Jl. Raden Intan No. 7',
                'asal_sekolah'  => 'SMAN 5 Bandar Lampung',
                'jurusan'       => 'Matematika',
                'no_telpon'     => '08789012346',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // TO23
            // 1
            [
                'kelas_id'      => '11',
                'jabatan_id'    => '1',
                'nim'           => '44556672',
                'nama'          => 'Dian Pratama',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Balikpapan',
                'tanggal_lahir' => '2002-05-15',
                'alamat'        => 'Jl. MT Haryono No. 22',
                'asal_sekolah'  => 'SMAN 2 Balikpapan',
                'jurusan'       => 'Teknik Mesin',
                'no_telpon'     => '08912345678',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],


        ])->each(function ($data) {
            Mahasiswa::create($data);
        });
    }
}
