<?php

namespace Database\Seeders;

use App\Models\Mahasiswa;
use Illuminate\Database\Seeder;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect([
            // MI24
            // 1
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2019023456',
                'nama'          => 'Ahmad Fadhli',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Bandung',
                'tanggal_lahir' => '2000-05-21',
                'alamat'        => 'Jl. Merdeka No. 10, Bandung',
                'asal_sekolah'  => 'SMA Negeri 1 Bandung',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '081234567890',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 2
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2018034567',
                'nama'          => 'Nina Rahmawati',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2001-07-15',
                'alamat'        => 'Jl. Sudirman No. 20, Jakarta',
                'asal_sekolah'  => 'SMA Negeri 5 Jakarta',
                'jurusan'       => 'Manajemen',
                'no_telpon'     => '081987654321',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 3
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2017045678',
                'nama'          => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Surabaya',
                'tanggal_lahir' => '1999-12-03',
                'alamat'        => 'Jl. Ahmad Yani No. 30, Surabaya',
                'asal_sekolah'  => 'SMA Negeri 3 Surabaya',
                'jurusan'       => 'Akuntansi',
                'no_telpon'     => '082345678901',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 4
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2016056789',
                'nama'          => 'Sri Wahyuni',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Yogyakarta',
                'tanggal_lahir' => '2000-01-25',
                'alamat'        => 'Jl. Malioboro No. 40, Yogyakarta',
                'asal_sekolah'  => 'SMA Negeri 2 Yogyakarta',
                'jurusan'       => 'Ilmu Komunikasi',
                'no_telpon'     => '081298765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 5
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2015067890',
                'nama'          => 'Andi Pratama',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Medan',
                'tanggal_lahir' => '1998-09-14',
                'alamat'        => 'Jl. Thamrin No. 50, Medan',
                'asal_sekolah'  => 'SMA Negeri 4 Medan',
                'jurusan'       => 'Sistem Informasi',
                'no_telpon'     => '082176543210',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 6
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2014078901',
                'nama'          => 'Rina Kurnia',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Bandar Lampung',
                'tanggal_lahir' => '2001-11-30',
                'alamat'        => 'Jl. Zainal Abidin No. 60, Bandar Lampung',
                'asal_sekolah'  => 'SMA Negeri 7 Bandar Lampung',
                'jurusan'       => 'Teknik Sipil',
                'no_telpon'     => '083298765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 7
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2013089012',
                'nama'          => 'Dian Susanti',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Palembang',
                'tanggal_lahir' => '1997-04-18',
                'alamat'        => 'Jl. Pangeran Antasari No. 70, Palembang',
                'asal_sekolah'  => 'SMA Negeri 6 Palembang',
                'jurusan'       => 'Hukum',
                'no_telpon'     => '081398765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 8
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2012090123',
                'nama'          => 'Yusuf Rahman',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Makassar',
                'tanggal_lahir' => '2000-08-25',
                'alamat'        => 'Jl. Pettarani No. 80, Makassar',
                'asal_sekolah'  => 'SMA Negeri 8 Makassar',
                'jurusan'       => 'Teknik Elektro',
                'no_telpon'     => '082389765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 9
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2011101234',
                'nama'          => 'Laila Putri',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Denpasar',
                'tanggal_lahir' => '2001-02-12',
                'alamat'        => 'Jl. Diponegoro No. 90, Denpasar',
                'asal_sekolah'  => 'SMA Negeri 2 Denpasar',
                'jurusan'       => 'Desain Komunikasi Visual',
                'no_telpon'     => '081498765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 10
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2010112345',
                'nama'          => 'Agus Saputra',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Pontianak',
                'tanggal_lahir' => '1999-06-05',
                'alamat'        => 'Jl. Gajah Mada No. 100, Pontianak',
                'asal_sekolah'  => 'SMA Negeri 1 Pontianak',
                'jurusan'       => 'Teknik Mesin',
                'no_telpon'     => '083498765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 11
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2019123456',
                'nama'          => 'Maya Sari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Semarang',
                'tanggal_lahir' => '2000-10-20',
                'alamat'        => 'Jl. Pemuda No. 110, Semarang',
                'asal_sekolah'  => 'SMA Negeri 9 Semarang',
                'jurusan'       => 'Psikologi',
                'no_telpon'     => '081598765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 12
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2018134567',
                'nama'          => 'Eko Prasetyo',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Balikpapan',
                'tanggal_lahir' => '2001-03-18',
                'alamat'        => 'Jl. Soekarno-Hatta No. 120, Balikpapan',
                'asal_sekolah'  => 'SMA Negeri 3 Balikpapan',
                'jurusan'       => 'Ekonomi',
                'no_telpon'     => '082498765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 13
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2017145678',
                'nama'          => 'Ratna Sari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Manado',
                'tanggal_lahir' => '2000-12-28',
                'alamat'        => 'Jl. Sam Ratulangi No. 130, Manado',
                'asal_sekolah'  => 'SMA Negeri 2 Manado',
                'jurusan'       => 'Farmasi',
                'no_telpon'     => '083598765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 14
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2016156789',
                'nama'          => 'Wawan Setiawan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Padang',
                'tanggal_lahir' => '2001-04-11',
                'alamat'        => 'Jl. Khatib Sulaiman No. 140, Padang',
                'asal_sekolah'  => 'SMA Negeri 4 Padang',
                'jurusan'       => 'Statistika',
                'no_telpon'     => '081698765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 15
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2015167890',
                'nama'          => 'Dewi Anjani',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Mataram',
                'tanggal_lahir' => '2000-07-29',
                'alamat'        => 'Jl. Pejanggik No. 150, Mataram',
                'asal_sekolah'  => 'SMA Negeri 3 Mataram',
                'jurusan'       => 'Kedokteran',
                'no_telpon'     => '082598765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 16
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2014178901',
                'nama'          => 'Firman Syah',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Banda Aceh',
                'tanggal_lahir' => '1999-05-02',
                'alamat'        => 'Jl. Teuku Umar No. 160, Banda Aceh',
                'asal_sekolah'  => 'SMA Negeri 1 Banda Aceh',
                'jurusan'       => 'Ilmu Politik',
                'no_telpon'     => '083698765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 17
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2013189012',
                'nama'          => 'Siti Fatimah',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Pekanbaru',
                'tanggal_lahir' => '2000-10-07',
                'alamat'        => 'Jl. Jendral Sudirman No. 170, Pekanbaru',
                'asal_sekolah'  => 'SMA Negeri 5 Pekanbaru',
                'jurusan'       => 'Keperawatan',
                'no_telpon'     => '081798765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 18
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2012190123',
                'nama'          => 'Hendra Wijaya',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Jambi',
                'tanggal_lahir' => '2001-11-03',
                'alamat'        => 'Jl. Pattimura No. 180, Jambi',
                'asal_sekolah'  => 'SMA Negeri 6 Jambi',
                'jurusan'       => 'Pertanian',
                'no_telpon'     => '082798765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 19
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2011201234',
                'nama'          => 'Rizki Maulana',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Bengkulu',
                'tanggal_lahir' => '1998-08-19',
                'alamat'        => 'Jl. Fatmawati No. 190, Bengkulu',
                'asal_sekolah'  => 'SMA Negeri 7 Bengkulu',
                'jurusan'       => 'Peternakan',
                'no_telpon'     => '083798765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 20
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2010212345',
                'nama'          => 'Sari Amalia',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Kupang',
                'tanggal_lahir' => '2000-12-09',
                'alamat'        => 'Jl. El Tari No. 200, Kupang',
                'asal_sekolah'  => 'SMA Negeri 8 Kupang',
                'jurusan'       => 'Pariwisata',
                'no_telpon'     => '081898765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 21
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2021223456',
                'nama'          => 'Aulia Rahma',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Palangkaraya',
                'tanggal_lahir' => '2001-09-15',
                'alamat'        => 'Jl. Rajawali No. 210, Palangkaraya',
                'asal_sekolah'  => 'SMA Negeri 10 Palangkaraya',
                'jurusan'       => 'Geologi',
                'no_telpon'     => '082898765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],
            // 22
            [
                'kelas_id'      => '1',
                'jabatan_id'    => '1',
                'nim'           => '2020234567',
                'nama'          => 'Rahmat Hidayat',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Ambon',
                'tanggal_lahir' => '1999-01-12',
                'alamat'        => 'Jl. Sultan Hasanuddin No. 220, Ambon',
                'asal_sekolah'  => 'SMA Negeri 11 Ambon',
                'jurusan'       => 'Teknik Geodesi',
                'no_telpon'     => '083898765432',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // MP05
            // 1
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345678',
                'nama'          => 'Ahmad Fauzan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2000-01-15',
                'alamat'        => 'Jl. Melati No. 5, Jakarta',
                'asal_sekolah'  => 'SMA Negeri 1 Jakarta',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '081234567890',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 2
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345679',
                'nama'          => 'Dewi Ayu',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Bandung',
                'tanggal_lahir' => '2001-02-20',
                'alamat'        => 'Jl. Kenanga No. 10, Bandung',
                'asal_sekolah'  => 'SMA Negeri 3 Bandung',
                'jurusan'       => 'Sistem Informasi',
                'no_telpon'     => '081345678901',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 3
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345680',
                'nama'          => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Surabaya',
                'tanggal_lahir' => '1999-12-10',
                'alamat'        => 'Jl. Mawar No. 15, Surabaya',
                'asal_sekolah'  => 'SMA Negeri 2 Surabaya',
                'jurusan'       => 'Teknik Elektro',
                'no_telpon'     => '081456789012',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 4
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345681',
                'nama'          => 'Citra Lestari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Medan',
                'tanggal_lahir' => '2000-05-25',
                'alamat'        => 'Jl. Anggrek No. 7, Medan',
                'asal_sekolah'  => 'SMA Negeri 4 Medan',
                'jurusan'       => 'Manajemen',
                'no_telpon'     => '081567890123',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 5
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345682',
                'nama'          => 'Doni Pratama',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Yogyakarta',
                'tanggal_lahir' => '2001-09-05',
                'alamat'        => 'Jl. Cempaka No. 11, Yogyakarta',
                'asal_sekolah'  => 'SMA Negeri 5 Yogyakarta',
                'jurusan'       => 'Teknik Mesin',
                'no_telpon'     => '081678901234',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 6
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345683',
                'nama'          => 'Eka Sari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Makassar',
                'tanggal_lahir' => '2002-03-14',
                'alamat'        => 'Jl. Dahlia No. 12, Makassar',
                'asal_sekolah'  => 'SMA Negeri 6 Makassar',
                'jurusan'       => 'Akuntansi',
                'no_telpon'     => '081789012345',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 7
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345684',
                'nama'          => 'Fajar Nugraha',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Semarang',
                'tanggal_lahir' => '2001-11-22',
                'alamat'        => 'Jl. Flamboyan No. 9, Semarang',
                'asal_sekolah'  => 'SMA Negeri 7 Semarang',
                'jurusan'       => 'Teknik Sipil',
                'no_telpon'     => '081890123456',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 8
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345685',
                'nama'          => 'Gita Permata',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Bali',
                'tanggal_lahir' => '2000-08-30',
                'alamat'        => 'Jl. Kamboja No. 3, Denpasar',
                'asal_sekolah'  => 'SMA Negeri 8 Bali',
                'jurusan'       => 'Desain Komunikasi Visual',
                'no_telpon'     => '081901234567',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 9
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345686',
                'nama'          => 'Hendri Wijaya',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Malang',
                'tanggal_lahir' => '2002-04-18',
                'alamat'        => 'Jl. Teratai No. 4, Malang',
                'asal_sekolah'  => 'SMA Negeri 9 Malang',
                'jurusan'       => 'Teknik Industri',
                'no_telpon'     => '082012345678',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 10
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345687',
                'nama'          => 'Indah Puspita',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Palembang',
                'tanggal_lahir' => '2001-07-07',
                'alamat'        => 'Jl. Bougenville No. 2, Palembang',
                'asal_sekolah'  => 'SMA Negeri 10 Palembang',
                'jurusan'       => 'Teknik Kimia',
                'no_telpon'     => '082123456789',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 11
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345688',
                'nama'          => 'Joko Prabowo',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Padang',
                'tanggal_lahir' => '2000-10-15',
                'alamat'        => 'Jl. Pahlawan No. 8, Padang',
                'asal_sekolah'  => 'SMA Negeri 11 Padang',
                'jurusan'       => 'Pendidikan Bahasa Inggris',
                'no_telpon'     => '082234567890',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 12
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345689',
                'nama'          => 'Kartika Sari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Banda Aceh',
                'tanggal_lahir' => '2001-06-06',
                'alamat'        => 'Jl. Merpati No. 1, Banda Aceh',
                'asal_sekolah'  => 'SMA Negeri 12 Banda Aceh',
                'jurusan'       => 'Ilmu Komunikasi',
                'no_telpon'     => '082345678901',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 13
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345690',
                'nama'          => 'Lukman Hakim',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Pekanbaru',
                'tanggal_lahir' => '2002-12-12',
                'alamat'        => 'Jl. Srikandi No. 14, Pekanbaru',
                'asal_sekolah'  => 'SMA Negeri 13 Pekanbaru',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '082456789012',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 14
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345691',
                'nama'          => 'Maya Putri',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Solo',
                'tanggal_lahir' => '2000-03-03',
                'alamat'        => 'Jl. Mangga No. 16, Solo',
                'asal_sekolah'  => 'SMA Negeri 14 Solo',
                'jurusan'       => 'Psikologi',
                'no_telpon'     => '082567890123',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 15
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345692',
                'nama'          => 'Nanda Kurniawan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Pontianak',
                'tanggal_lahir' => '2001-01-25',
                'alamat'        => 'Jl. Karet No. 17, Pontianak',
                'asal_sekolah'  => 'SMA Negeri 15 Pontianak',
                'jurusan'       => 'Teknik Pertanian',
                'no_telpon'     => '082678901234',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 16
            [
                'kelas_id'      => '2',
                'jabatan_id'    => '1',
                'nim'           => '0012345693',
                'nama'          => 'Olivia Permana',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Manado',
                'tanggal_lahir' => '2002-09-15',
                'alamat'        => 'Jl. Cemara No. 18, Manado',
                'asal_sekolah'  => 'SMA Negeri 16 Manado',
                'jurusan'       => 'Biologi',
                'no_telpon'     => '082789012345',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // MKP05
            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '938471647',
                'nama'          => 'Arif Wijaya',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Bandung',
                'tanggal_lahir' => '2000-05-21',
                'alamat'        => 'Jl. Merdeka No. 10',
                'asal_sekolah'  => 'SMA Negeri 1 Bandung',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '081234567890',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //1

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '987654300',
                'nama'          => 'Siti Nurhaliza',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2001-02-14',
                'alamat'        => 'Jl. Sudirman No. 5',
                'asal_sekolah'  => 'SMA Negeri 2 Jakarta',
                'jurusan'       => 'Sistem Informasi',
                'no_telpon'     => '081234567891',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //2

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '112233446',
                'nama'          => 'Dewi Lestari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Surabaya',
                'tanggal_lahir' => '1999-07-30',
                'alamat'        => 'Jl. Diponegoro No. 15',
                'asal_sekolah'  => 'SMA Negeri 5 Surabaya',
                'jurusan'       => 'Teknik Elektro',
                'no_telpon'     => '081234567892',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //3

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '919510229',
                'nama'          => 'Ahmad Fauzi',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Yogyakarta',
                'tanggal_lahir' => '2000-10-15',
                'alamat'        => 'Jl. Malioboro No. 20',
                'asal_sekolah'  => 'SMA Negeri 3 Yogyakarta',
                'jurusan'       => 'Teknik Mesin',
                'no_telpon'     => '081234567893',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //4

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '445566754',
                'nama'          => 'Rina Setiawati',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Malang',
                'tanggal_lahir' => '2001-11-20',
                'alamat'        => 'Jl. Ijen No. 12',
                'asal_sekolah'  => 'SMA Negeri 4 Malang',
                'jurusan'       => 'Teknik Sipil',
                'no_telpon'     => '081234567894',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //5

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '334455825',
                'nama'          => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Semarang',
                'tanggal_lahir' => '1999-12-25',
                'alamat'        => 'Jl. Pandanaran No. 9',
                'asal_sekolah'  => 'SMA Negeri 6 Semarang',
                'jurusan'       => 'Teknik Kimia',
                'no_telpon'     => '081234567895',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //6

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '778899017',
                'nama'          => 'Indra Lesmana',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Denpasar',
                'tanggal_lahir' => '2000-03-10',
                'alamat'        => 'Jl. Raya Kuta No. 8',
                'asal_sekolah'  => 'SMA Negeri 2 Denpasar',
                'jurusan'       => 'Teknik Arsitektur',
                'no_telpon'     => '081234567896',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //7

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '551788245',
                'nama'          => 'Agus Supriyadi',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Bandar Lampung',
                'tanggal_lahir' => '2001-04-05',
                'alamat'        => 'Jl. Raden Intan No. 3',
                'asal_sekolah'  => 'SMA Negeri 7 Bandar Lampung',
                'jurusan'       => 'Teknik Industri',
                'no_telpon'     => '081234567897',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //8

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '990019223',
                'nama'          => 'Fitri Aulia',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Makassar',
                'tanggal_lahir' => '1998-08-22',
                'alamat'        => 'Jl. Pettarani No. 14',
                'asal_sekolah'  => 'SMA Negeri 8 Makassar',
                'jurusan'       => 'Teknik Lingkungan',
                'no_telpon'     => '081234567898',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //9

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '223344556',
                'nama'          => 'Lukman Hakim',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Padang',
                'tanggal_lahir' => '2000-09-12',
                'alamat'        => 'Jl. Sudirman No. 17',
                'asal_sekolah'  => 'SMA Negeri 10 Padang',
                'jurusan'       => 'Teknik Geodesi',
                'no_telpon'     => '081234567899',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //10

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '887766554',
                'nama'          => 'Wulan Sari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Palembang',
                'tanggal_lahir' => '2001-01-18',
                'alamat'        => 'Jl. Jendral Sudirman No. 23',
                'asal_sekolah'  => 'SMA Negeri 11 Palembang',
                'jurusan'       => 'Teknik Komputer',
                'no_telpon'     => '081234567800',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //11

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '332211445',
                'nama'          => 'Rahmat Hidayat',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Pontianak',
                'tanggal_lahir' => '1999-06-11',
                'alamat'        => 'Jl. Gajah Mada No. 2',
                'asal_sekolah'  => 'SMA Negeri 12 Pontianak',
                'jurusan'       => 'Teknik Telekomunikasi',
                'no_telpon'     => '081234567801',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //12

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '776655443',
                'nama'          => 'Nurul Aini',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Banjarmasin',
                'tanggal_lahir' => '2000-12-02',
                'alamat'        => 'Jl. Ahmad Yani No. 19',
                'asal_sekolah'  => 'SMA Negeri 13 Banjarmasin',
                'jurusan'       => 'Teknik Penerbangan',
                'no_telpon'     => '081234567802',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //13

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '009988776',
                'nama'          => 'Eko Prasetyo',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Palangkaraya',
                'tanggal_lahir' => '1998-11-15',
                'alamat'        => 'Jl. Tjilik Riwut No. 4',
                'asal_sekolah'  => 'SMA Negeri 14 Palangkaraya',
                'jurusan'       => 'Teknik Nuklir',
                'no_telpon'     => '081234567803',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //14

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '445522337',
                'nama'          => 'Rizki Ramadhan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Manado',
                'tanggal_lahir' => '2001-07-07',
                'alamat'        => 'Jl. Sam Ratulangi No. 18',
                'asal_sekolah'  => 'SMA Negeri 15 Manado',
                'jurusan'       => 'Teknik Material',
                'no_telpon'     => '081234567804',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //15

            [
                'kelas_id'      => '3',
                'jabatan_id'    => '1',
                'nim'           => '667788995',
                'nama'          => 'Anita Sari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Pekanbaru',
                'tanggal_lahir' => '1999-03-29',
                'alamat'        => 'Jl. Riau No. 21',
                'asal_sekolah'  => 'SMA Negeri 16 Pekanbaru',
                'jurusan'       => 'Teknik Perminyakan',
                'no_telpon'     => '081234567805',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ], //16



            // AB18
            // 1
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234567',
                'nama'          => 'Rizki Putra',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2000-10-12',
                'alamat'        => 'Jl. Merdeka No. 1, Jakarta',
                'asal_sekolah'  => 'SMA Negeri 1 Jakarta',
                'jurusan'       => 'Ekonomi',
                'no_telpon'     => '081212345678',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 2
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234568',
                'nama'          => 'Ayu Lestari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Bandung',
                'tanggal_lahir' => '2001-05-25',
                'alamat'        => 'Jl. Sudirman No. 2, Bandung',
                'asal_sekolah'  => 'SMA Negeri 3 Bandung',
                'jurusan'       => 'Psikologi',
                'no_telpon'     => '081234567891',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 3
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234569',
                'nama'          => 'Andi Wijaya',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Surabaya',
                'tanggal_lahir' => '2000-11-30',
                'alamat'        => 'Jl. Pahlawan No. 5, Surabaya',
                'asal_sekolah'  => 'SMA Negeri 2 Surabaya',
                'jurusan'       => 'Teknik Elektro',
                'no_telpon'     => '081345678902',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 4
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234570',
                'nama'          => 'Bunga Sari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Medan',
                'tanggal_lahir' => '2001-07-15',
                'alamat'        => 'Jl. Imam Bonjol No. 7, Medan',
                'asal_sekolah'  => 'SMA Negeri 4 Medan',
                'jurusan'       => 'Sastra Indonesia',
                'no_telpon'     => '081456789013',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 5
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234571',
                'nama'          => 'Dewi Anggraini',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Yogyakarta',
                'tanggal_lahir' => '2001-03-10',
                'alamat'        => 'Jl. Malioboro No. 3, Yogyakarta',
                'asal_sekolah'  => 'SMA Negeri 5 Yogyakarta',
                'jurusan'       => 'Arsitektur',
                'no_telpon'     => '081567890124',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 6
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234572',
                'nama'          => 'Eko Saputra',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Makassar',
                'tanggal_lahir' => '2000-09-18',
                'alamat'        => 'Jl. Hasanuddin No. 10, Makassar',
                'asal_sekolah'  => 'SMA Negeri 6 Makassar',
                'jurusan'       => 'Teknik Mesin',
                'no_telpon'     => '081678901235',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 7
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234573',
                'nama'          => 'Fauzi Ramadhan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Semarang',
                'tanggal_lahir' => '2002-02-20',
                'alamat'        => 'Jl. Kartini No. 4, Semarang',
                'asal_sekolah'  => 'SMA Negeri 7 Semarang',
                'jurusan'       => 'Ilmu Hukum',
                'no_telpon'     => '081789012346',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 8
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234574',
                'nama'          => 'Gina Amalia',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Palembang',
                'tanggal_lahir' => '2000-06-11',
                'alamat'        => 'Jl. Merpati No. 12, Palembang',
                'asal_sekolah'  => 'SMA Negeri 10 Palembang',
                'jurusan'       => 'Manajemen',
                'no_telpon'     => '081890123457',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 9
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234575',
                'nama'          => 'Hendra Wijaya',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Padang',
                'tanggal_lahir' => '2001-12-22',
                'alamat'        => 'Jl. Sudirman No. 9, Padang',
                'asal_sekolah'  => 'SMA Negeri 11 Padang',
                'jurusan'       => 'Ilmu Komunikasi',
                'no_telpon'     => '081901234568',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 10
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234576',
                'nama'          => 'Indah Pertiwi',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Solo',
                'tanggal_lahir' => '2001-08-14',
                'alamat'        => 'Jl. Mangga No. 6, Solo',
                'asal_sekolah'  => 'SMA Negeri 14 Solo',
                'jurusan'       => 'Pendidikan Bahasa Inggris',
                'no_telpon'     => '082012345679',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 11
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234577',
                'nama'          => 'Joko Santoso',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Denpasar',
                'tanggal_lahir' => '2000-04-19',
                'alamat'        => 'Jl. Kamboja No. 3, Denpasar',
                'asal_sekolah'  => 'SMA Negeri 8 Denpasar',
                'jurusan'       => 'Teknik Sipil',
                'no_telpon'     => '082123456790',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 12
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234578',
                'nama'          => 'Kartika Putri',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Pekanbaru',
                'tanggal_lahir' => '2001-09-09',
                'alamat'        => 'Jl. Srikandi No. 11, Pekanbaru',
                'asal_sekolah'  => 'SMA Negeri 13 Pekanbaru',
                'jurusan'       => 'Desain Komunikasi Visual',
                'no_telpon'     => '082234567801',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 13
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234579',
                'nama'          => 'Lukman Hakim',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Bandung',
                'tanggal_lahir' => '2000-07-07',
                'alamat'        => 'Jl. Cihampelas No. 8, Bandung',
                'asal_sekolah'  => 'SMA Negeri 15 Bandung',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '082345678912',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 14
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234580',
                'nama'          => 'Maya Putri',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Solo',
                'tanggal_lahir' => '2000-03-03',
                'alamat'        => 'Jl. Mangga No. 16, Solo',
                'asal_sekolah'  => 'SMA Negeri 14 Solo',
                'jurusan'       => 'Psikologi',
                'no_telpon'     => '082456789013',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 15
            [
                'kelas_id'      => '4',
                'jabatan_id'    => '1',
                'nim'           => '0041234581',
                'nama'          => 'Nanda Kurniawan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Pontianak',
                'tanggal_lahir' => '2001-01-25',
                'alamat'        => 'Jl. Karet No. 17, Pontianak',
                'asal_sekolah'  => 'SMA Negeri 15 Pontianak',
                'jurusan'       => 'Teknik Pertanian',
                'no_telpon'     => '082567890124',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // TO24
            // 1
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123456',
                'nama'          => 'Andi Pratama',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Bandung',
                'tanggal_lahir' => '2001-04-15',
                'alamat'        => 'Jl. Merdeka No. 123, Bandung',
                'asal_sekolah'  => 'SMA 1 Bandung',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '081234567890',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 2
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123457',
                'nama'          => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Jakarta',
                'tanggal_lahir' => '2000-11-25',
                'alamat'        => 'Jl. Sudirman No. 45, Jakarta',
                'asal_sekolah'  => 'SMA 3 Jakarta',
                'jurusan'       => 'Sistem Informasi',
                'no_telpon'     => '081234567891',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 3
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123458',
                'nama'          => 'Citra Dewi',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Surabaya',
                'tanggal_lahir' => '2001-07-10',
                'alamat'        => 'Jl. Ahmad Yani No. 76, Surabaya',
                'asal_sekolah'  => 'SMA 2 Surabaya',
                'jurusan'       => 'Teknik Komputer',
                'no_telpon'     => '081234567892',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 4
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123459',
                'nama'          => 'Dedi Rahmat',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Yogyakarta',
                'tanggal_lahir' => '2001-02-12',
                'alamat'        => 'Jl. Malioboro No. 99, Yogyakarta',
                'asal_sekolah'  => 'SMA 4 Yogyakarta',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '081234567893',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 5
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123460',
                'nama'          => 'Eka Susanti',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Semarang',
                'tanggal_lahir' => '2000-09-30',
                'alamat'        => 'Jl. Pandanaran No. 12, Semarang',
                'asal_sekolah'  => 'SMA 5 Semarang',
                'jurusan'       => 'Sistem Informasi',
                'no_telpon'     => '081234567894',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 6
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123461',
                'nama'          => 'Fajar Setiawan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Malang',
                'tanggal_lahir' => '2001-05-20',
                'alamat'        => 'Jl. Ijen No. 18, Malang',
                'asal_sekolah'  => 'SMA 6 Malang',
                'jurusan'       => 'Teknik Komputer',
                'no_telpon'     => '081234567895',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 7
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123462',
                'nama'          => 'Gita Ayu',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Medan',
                'tanggal_lahir' => '2001-03-05',
                'alamat'        => 'Jl. Gatot Subroto No. 56, Medan',
                'asal_sekolah'  => 'SMA 7 Medan',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '081234567896',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 8
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123463',
                'nama'          => 'Hendra Putra',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Palembang',
                'tanggal_lahir' => '2000-12-18',
                'alamat'        => 'Jl. Veteran No. 23, Palembang',
                'asal_sekolah'  => 'SMA 8 Palembang',
                'jurusan'       => 'Sistem Informasi',
                'no_telpon'     => '081234567897',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 9
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123464',
                'nama'          => 'Indah Sari',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Makassar',
                'tanggal_lahir' => '2001-08-22',
                'alamat'        => 'Jl. Pettarani No. 34, Makassar',
                'asal_sekolah'  => 'SMA 9 Makassar',
                'jurusan'       => 'Teknik Komputer',
                'no_telpon'     => '081234567898',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 10
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123465',
                'nama'          => 'Joko Widodo',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Solo',
                'tanggal_lahir' => '2001-10-14',
                'alamat'        => 'Jl. Slamet Riyadi No. 12, Solo',
                'asal_sekolah'  => 'SMA 10 Solo',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '081234567899',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 11
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123466',
                'nama'          => 'Kartini Pertiwi',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Denpasar',
                'tanggal_lahir' => '2000-07-01',
                'alamat'        => 'Jl. Diponegoro No. 77, Denpasar',
                'asal_sekolah'  => 'SMA 11 Denpasar',
                'jurusan'       => 'Sistem Informasi',
                'no_telpon'     => '081234567900',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 12
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123467',
                'nama'          => 'Lutfi Amalia',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Balikpapan',
                'tanggal_lahir' => '2000-05-10',
                'alamat'        => 'Jl. MT Haryono No. 90, Balikpapan',
                'asal_sekolah'  => 'SMA 12 Balikpapan',
                'jurusan'       => 'Teknik Komputer',
                'no_telpon'     => '081234567901',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 13
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123468',
                'nama'          => 'Maya Larasati',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Bandung',
                'tanggal_lahir' => '2001-03-30',
                'alamat'        => 'Jl. Riau No. 45, Bandung',
                'asal_sekolah'  => 'SMA 13 Bandung',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '081234567902',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 14
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123469',
                'nama'          => 'Nina Suryani',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir'  => 'Cirebon',
                'tanggal_lahir' => '2001-02-28',
                'alamat'        => 'Jl. Siliwangi No. 67, Cirebon',
                'asal_sekolah'  => 'SMA 14 Cirebon',
                'jurusan'       => 'Sistem Informasi',
                'no_telpon'     => '081234567903',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],

            // 15
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123470',
                'nama'          => 'Oka Dharmawan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Pontianak',
                'tanggal_lahir' => '2000-06-17',
                'alamat'        => 'Jl. Ahmad Yani No. 88, Pontianak',
                'asal_sekolah'  => 'SMA 15 Pontianak',
                'jurusan'       => 'Teknik Komputer',
                'no_telpon'     => '081234567904',
                'status_ukm'    => 'Anggota LCC',
                'alasan'        => '-',
            ],

            // 16
            [
                'kelas_id'      => '5',
                'jabatan_id'    => '1',
                'nim'           => '005123471',
                'nama'          => 'Putu Ariawan',
                'jenis_kelamin' => 'Laki-Laki',
                'tempat_lahir'  => 'Gianyar',
                'tanggal_lahir' => '2001-11-11',
                'alamat'        => 'Jl. Raya Ubud No. 50, Gianyar',
                'asal_sekolah'  => 'SMA 16 Gianyar',
                'jurusan'       => 'Teknik Informatika',
                'no_telpon'     => '081234567905',
                'status_ukm'    => 'Bukan Anggota',
                'alasan'        => '-',
            ],


        ])->each(function ($data) {
            Mahasiswa::create($data);
        });
    }
}
