<?php

namespace Database\Seeders;

use App\Models\Mahasiswa;
use Illuminate\Database\Seeder;

class MahasiswaMISeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect([
            // MI23A
            // 1
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302002',
                'nama'          =>'Aceng Ziran Fauji',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 2
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302074',
                'nama'          =>'Yogi Febriandi',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 3
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302049',
                'nama'          =>'Tazkia Hidayatuloh AL M.',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 4
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302034',
                'nama'          =>'Andika Herviantino P.',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 5
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302050',
                'nama'          =>'Sinta Aulia Wardani',
                'jenis_kelamin' =>'Perempuan',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 6
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302057',
                'nama'          =>'Arapian Hapiz',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Anggota LCC',
            ],
            // 7
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302029',
                'nama'          =>'Rian Afrizal',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 8
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302053',
                'nama'          =>'Dimas Novi Fitriansyah',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 9
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302039',
                'nama'          =>'Rangga Dwiky Rokhman P.',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Anggota LCC',
            ],
            // 10
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302015',
                'nama'          =>'Emil Awaliadi',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 11
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302094',
                'nama'          =>'Puji Haryadi',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 12
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302003',
                'nama'          =>'Fazhari Rizky',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Anggota LCC',
            ],
            // 13
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302005',
                'nama'          =>'Muhammad Rasyid Ridho',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 14
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302054',
                'nama'          =>'Kevin Leonardo',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 15
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302016',
                'nama'          =>'Muhammad Farhan Saefulloh',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 16
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302064',
                'nama'          =>'Muhamad Arfan Maulana',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 17
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302056',
                'nama'          =>'Muhammad Ali Akbar A. A.',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 18
            [
                'kelas_id'      =>'1',
                'nim'           =>'202302088',
                'nama'          =>'Muhamad Irfan Sujono',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // End MI23A

            // MI23B
            // 1
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302028',
                'nama'          =>'Adi Aprianto',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Anggota LCC',
            ],
            // 2
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302035',
                'nama'          =>'Teguh Afriansyah',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Anggota LCC',
            ],
            // 3
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302037',
                'nama'          =>'Azwan Faisal',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 4
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302000',
                'nama'          =>'Shandy Febriansyah',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 5
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302086',
                'nama'          =>'Dede Muhammad Walid A.',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 6
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302059',
                'nama'          =>'Rizki Firdaus',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 7
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302060',
                'nama'          =>'Deki Inawan',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 8
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302004',
                'nama'          =>'Reni Nurhayni',
                'jenis_kelamin' =>'Perempuan',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Anggota LCC',
            ],
            // 9
            [
                'kelas_id'      =>'2',
                'nim'           =>'2023020',
                'nama'          =>'Djohara Ariefin Haqim H.',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 10
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302051',
                'nama'          =>'Raga Kusnira',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 11
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302006',
                'nama'          =>'Ikhsan Tazkia Muhammad F.',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 12
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302077',
                'nama'          =>'Muhammad Rafi Assidiqi',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 13
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302036',
                'nama'          =>'Khikmal Kurniawan',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Anggota LCC',
            ],
            // 14
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302040',
                'nama'          =>'Muhammad Arfan Algibrani',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 15
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302055',
                'nama'          =>'Mohammad Khalil Ardhani',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Anggota LCC',
            ],
            // 16
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302033',
                'nama'          =>'Muhammad Abdur Rouf',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 17
            [
                'kelas_id'      =>'2',
                'nim'           =>'202302087',
                'nama'          =>'Muhamad Faisal Abdallah',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Bukan Anggota',
            ],
            // 18
            [
                'kelas_id'      =>'2',
                'nim'           =>'20230201',
                'nama'          =>'Panja Alzikri Hidayat',
                'jenis_kelamin' =>'Laki-Laki',
                'tempat_lahir'  =>'-',
                'tanggal_lahir' =>'2000-01-01',
                'alamat'        =>'-',
                'asal_sekolah'  =>'-',
                'jurusan'       =>'-',
                'no_telpon'     =>'000000000000',
                'status_ukm'    =>'Anggota LCC',
            ],
            // End MI23B
        ])->each(function($data){
            Mahasiswa::create($data);
        });
    }
}
